### ISSUE TITLE
MetricsEndpointMiddleware doesn't satisfy AllowSynchronousIO option of Kestrel server

### ISSUE THREAD

**Issue by stukselbax** [AppMetrics/AspNetCore#51]
Recently we started migration to the prometheus engine to store our metrics, so we used the /metrics endpoint processed by this library. Also we have configured it with prometheus formatter.

```c#

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost
                .CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseMetrics()
                .UseMetricsEndpoints(options =>
                {
                    options.MetricsEndpointOutputFormatter = new MetricsPrometheusTextOutputFormatter();
                })
                .UseKestrel(o => o.AllowSynchronousIO = false);
    }
```

There is an option in kestrel server which disable synchronous api in order to prevent potential blocking of threads. So what we observing is if `AllowSynchronousIO == false`, the formatters of library throw since they use synchronous methods when writing to the stream:

```text
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.WriteSimpleValue(StreamWriter writer, String family, Double value, IEnumerable`1 labels, String namePostfix) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\Internal\AsciiFormatter.cs:line 115
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.WriteMetric(StreamWriter streamWriter, MetricFamily family, Metric metric) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\Internal\AsciiFormatter.cs:line 110
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.WriteFamily(StreamWriter streamWriter, MetricFamily metricFamily) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\Internal\AsciiFormatter.cs:line 58
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.Write(Stream destination, IEnumerable`1 metrics, NewLineFormat newLine) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\Internal\AsciiFormatter.cs:line 36
   at App.Metrics.Formatters.Prometheus.MetricsPrometheusTextOutputFormatter.WriteAsync(Stream output, MetricsDataValueSource metricsData, CancellationToken cancellationToken) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\MetricsPrometheusTextOutputFormatter.cs:line 47
   at App.Metrics.AspNetCore.Endpoints.Middleware.MetricsEndpointMiddleware.Invoke(HttpContext context) in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Endpoints\Middleware\MetricsEndpointMiddleware.cs:line 41
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

As for now we have to set `AllowSynchronousIO == true`, but I think the library must be [async all the way](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx). The same behavior observed with default output formatter, and with /metrics-text default output formater. Checked with 2.0 and 3.0 versions of app.metrics, and with aspnetcore 2.1 and 2.2.

**Comment by stukselbax** [comment]
FYI #aspnet/AspNetCore/issues/7644
